name: Update Substack Articles
on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Update README with Substack posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://ricardoledan.substack.com/feed"
          max_post_count: 5
          readme_path: "./README.md"
          comment_tag_name: "SUBSTACK"
          user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
          commit_message: "📝 Updated Substack articles"
          committer_username: "substack-bot"
          committer_email: "action@github.com"