name: Update Substack Articles
on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README with Substack posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://ricardoledan.substack.com/feed"
          max_post_count: 5
          readme_path: "./README.md"
          comment_tag_name: "SUBSTACK"